-- Adds the customisable profile-photo ring to existing board_members tables.
--
-- db/schema.sql is all CREATE TABLE IF NOT EXISTS, so it does nothing to a
-- table that already exists — a new column has to be added explicitly. SQLite
-- has no ADD COLUMN IF NOT EXISTS, so this runs exactly once per database and
-- errors if repeated. That is the trade recorded in CLAUDE.md: a schema this
-- small does not justify `wrangler d1 migrations` yet, but this is the second
-- schema change, so the next one probably does.
--
--   npm run db:patch:local  -- db/migrations/2026-09-board-member-accent.sql
--   npm run db:patch:remote -- db/migrations/2026-09-board-member-accent.sql
ALTER TABLE board_members ADD COLUMN accent TEXT NOT NULL DEFAULT 'green';
